#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

# run step 0 to step 5 by default
stage=-1
stop_stage=4
num_mel_bins=128

dl_dir=$PWD/download
fbank_dir=data/fbank

# we assume that you have your downloaded the AudioSet and placed
# it under $dl_dir/audioset, the folder structure should look like
# this:
# - $dl_dir/voxceleb
# If you haven't downloaded the AudioSet, please refer to
# https://github.com/RicherMans/SAT/blob/main/datasets/audioset/1_download_audioset.sh.

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare_voxceleb.sh"

log "dl_dir: $dl_dir"

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
    log "Stage 0: Compute fbank for VoxCeleb and generate manifest"
    log "You need to first download VoxCeleb1 and VoxCeleb2 to $dl_dir"
    log "After downloading, convert the w4a to wav: https://gist.github.com/seungwonpark/4f273739beef2691cd53b5c39629d830"
    
    if [ ! -e $fbank_dir/.voxceleb.done ]; then
        for dataset in vox2; do
            for part in dev test; do
                python ./local/generate_voxceleb_manifest.py \
                    --dataset $dataset \
                    --part $part \
                    --manifest-output-dir ${fbank_dir}/${dataset}_cuts_${part}.jsonl.gz \
                    --num-mel-bins $num_mel_bins
            done
        done
        touch ${fbank_dir}/.voxceleb.done
    fi

    log "Download the evaluate pairs"
    wget https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt -P $dl_dir
fi
